[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bids-mosaic"
version = "0.0.1"
dependencies = [
    "numpy",
    "pybids",
    "nilearn",
    "fpdf2",
    "pillow"
]
